# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50f1f9974c9fc11894d44530fa6666656708c484cecc8e0a7cc903300c67fcf4bfdf7b253790ba4cdc6b6ba6a75ed7d4fbcab66c7b44fd704912cfece40b7a46

test:
  secret_key_base: 6d1d3af6ec93592611f31aad216cc823803f3446f50186eac1b3ea2581474a83ffcf48d878c424399d9aa4d99b186e59260477b7421dd6da3e22dd0e5163c46a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
